format = """
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$golang\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false